wsgi/myproject/myproject/urls.py
"""
RPC Django on Openshift
"""
from django.conf.urls import include, url
from django.contrib import admin

from django.contrib.auth import views as auth_views

from rest_framework.authtoken import views as token_views
from rest_framework import routers
import users.views
from django.views.generic import TemplateView
# For default registration functionality
from django.views.generic.edit import CreateView
from users.forms import RegisterForm
import photos.views
import photos.forms
import inventory.views

router = routers.DefaultRouter()
router.register(r'users', users.views.UserViewSet)
router.register(r'groups', users.views.GroupViewSet)
router.register(r'photos', photos.views.BasicPhotoViewSet)
router.register(r'albums', photos.views.AlbumViewSet)
router.register(r'album_photo', photos.views.AlbumPhotoViewSet)
router.register(r'product', inventory.views.ProductViewSet)

router.register(r'quantity', inventory.views.ProductQuantityViewSet)

router.register(r'inventory', inventory.views.InventoryViewSet)

# Use this to override registration/login; i.e. DRY for login template
login_template = {'template_name': 'rest_framework/login.html'}

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="base.html")),

    # Next two URLS are for public user registration
    # For displaying messages/data in /success, use a CBV constructed
    # from both SuccessMessageMixin + CreateView
    url(r"^success/$", TemplateView.as_view(template_name="registration/success.html")),
    url(r'^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=RegisterForm,
            success_url='/success/'
    ), name='create_normal_user'),

    # change password, etc
    # login here overrides the included one below
    url(r'^accounts/login/',  auth_views.login, login_template, name="login"),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include(router.urls, namespace="api")),

    url(r'^upload-photo/'
      , TemplateView.as_view(template_name='photos/index.html')
      , name='upload-photo-form'),

    url(r'^upload-photo-post/', photos.views.basic_photo_upload, name='upload-photo'),

    url(r'^api-token-auth/', token_views.obtain_auth_token),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

wsgi/myproject/templates/base.html
<html>
    <head>
    <!DOCTYPE html>
<html lang="en">
<head>
    {% block header_styles %}{% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    {% block bootstrap_head %}

    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous"> -->
    <link rel="stylesheet" href="http://bootswatch.com/flatly/bootstrap.min.css" type="text/css">

    {% endblock %}

    {% block header_js %}
    {% endblock %}

</head>

<body>
    {% block nav %}
    <nav class="navbar navbar-default" style="border-radius: 0px;" >
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#">RP Codes<br></a>
            <!-- <small>Exchange</small></a> -->

        </div>

        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <!-- dropdowns
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Customer
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/customer/">Add/Edit Customer</a></li>
              <li><a href="/invoice/">Invoice</a></li>
              <li><a href="/activity/">Sales</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Driver
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/driver/">Add/Edit Driver</a></li>
              <li><a href="/map/">Show GPS Map</a></li>
              <li><a href="/assignments/">Delivery Assignments</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Exchange
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/inventory/">Exchange Site Overview</a></li>
              <li><a href="/map/">Show GPS Map</a></li>
              <li><a href="/assignments/">Delivery Assignments</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tools
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/override/customer/">Credit/Debit Customer</a></li>
              <li><a href="/override/delivery/">Manual Delivery Assignment</a></li>
              <li><a href="/override/driver/">View Driver Requests</a></li>
              <li><a href="/override/driver/">System Permissions</a></li>
              <li><a href="/info/">Update HQ Info</a></li>
            </ul>
          </li>
        </ul>-->
        <!--
        <li id="navCustomer"><a href="/etc/">Exchange Tank Inventory App</a></li>
        -->
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <!-- login/out -->
            {% if user.is_authenticated %}
                <li><a href="{% url 'rest_framework:logout' %}">Log out {{ user.username }}</a></li>
            {% else %}
                <li><a href="{% url 'rest_framework:login' %}">Log in</a></li>
            {% endif %}
        </ul>
        </div>
    </div>
    </nav>
    {% endblock %}
    {% block content %}

    {% endblock %}
    {% block foot %}

    <footer class="container-fluid "><br>
        <div class="row">
        <div class=" col-sm-3"></div>
        <div class=" col-sm-5">
            <!-- <span class="text-right label label-primary">S & F Gasworks</span> -->
        </div>
        <div class=" col-sm-3 "></div>
        </div>
    </footer>
    {% endblock %}
    {% block bootstrap_js %}
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% endblock %}
    {% block footer_js %}

    {% endblock %}

</body>
</html>

wsgi/myproject/templates/register.html
{% extends "base.html" %}
{% block header_styles %}
<style>
    div.err {
        margin-right: 5em;
        padding: 0.5em;
        border-left: solid #990000 3px;
        color: #990000;
    }
    .status-wrapper {
        padding: 1em
    }
    .field-wrapper {
        
    }
</style>
{% endblock %}
{% block content %}
<div class="container-fluid">
{% if user.is_authenticated %}
<h3>Welcome, {{ user.username }}.</h3>
{% else %}
<form class="form-horizontal" id="userform" style="padding: 0 5em;">
      <div class="form-group text-center status-wrapper">
        
        <span id="status" class="label label-primary">
           Please Register your account below; or <a href="{% url 'rest_framework:login' %}"
           >Login</a>.
       </span>
        
    </div>
    <!-- get csrf from cookie {% csrf_token %}-->
    <div class="form-group" >
      <label class="col-sm-2" for="first_name">First Name</label>
      <div class="col-sm-4 field-wrapper">
        <input type="text" name="first_name" id="first_name"/>
      </div>
    <!--</div>
    <div class="form-group" >-->
      <label class="col-sm-2" for="last_name">Last Name</label>
      <div class="col-sm-4 field-wrapper">
        <input type="text" name="last_name" id="last_name"/>
      </div>
    </div>
    <div class="form-group" >
      <label class="col-sm-2" for="username">Username *</label>
      <div class="col-sm-4 field-wrapper">
        <input type="text" name="username" id="username"/>
      </div>
    <!-- </div><div class="form-group"> -->
      <label class="col-sm-2" for="password">Password *</label>
       <div class="col-sm-4 field-wrapper">
        <input type="text" name="password" id="password"/>
        </div>
    </div>
    <div class="form-group" >
      <label class="col-sm-2" for="email">Email</label>
      <div class="col-sm-4 field-wrapper">
        <input type="text"name="email" id="email"/>
      </div>
      <div class="col-sm-6"></div>
    </div>
   
    <div class="form-group" >
    
    <!-- TODO: Also check for role, in case a Driver hacks his way here ;) -->
    <div class="col-sm-4">
        <input class="btn btn-primary" type="submit" value="Submit">
    </div>
    <small class="text-right col-sm-8"><b>* - required</b></small>
   
    
</form>
{% endif %}
{% endblock %}